export type BibleBook = {
  id: string;
  name: string; // FR
  apiName: string; // EN for bible-api.com
  slug: string; // for CDN-based APIs
  chapters: number;
  testament: 'OT' | 'NT';
};

export const BIBLE_BOOKS: BibleBook[] = [
  { id: 'gen', name: 'Genèse', apiName: 'Genesis', slug: 'genesis', chapters: 50, testament: 'OT' },
  { id: 'exo', name: 'Exode', apiName: 'Exodus', slug: 'exodus', chapters: 40, testament: 'OT' },
  { id: 'lev', name: 'Lévitique', apiName: 'Leviticus', slug: 'leviticus', chapters: 27, testament: 'OT' },
  { id: 'num', name: 'Nombres', apiName: 'Numbers', slug: 'numbers', chapters: 36, testament: 'OT' },
  { id: 'deu', name: 'Deutéronome', apiName: 'Deuteronomy', slug: 'deuteronomy', chapters: 34, testament: 'OT' },
  { id: 'jos', name: 'Josué', apiName: 'Joshua', slug: 'joshua', chapters: 24, testament: 'OT' },
  { id: 'jdg', name: 'Juges', apiName: 'Judges', slug: 'judges', chapters: 21, testament: 'OT' },
  { id: 'rut', name: 'Ruth', apiName: 'Ruth', slug: 'ruth', chapters: 4, testament: 'OT' },
  { id: '1sa', name: '1 Samuel', apiName: '1 Samuel', slug: '1-samuel', chapters: 31, testament: 'OT' },
  { id: '2sa', name: '2 Samuel', apiName: '2 Samuel', slug: '2-samuel', chapters: 24, testament: 'OT' },
  { id: '1ki', name: '1 Rois', apiName: '1 Kings', slug: '1-kings', chapters: 22, testament: 'OT' },
  { id: '2ki', name: '2 Rois', apiName: '2 Kings', slug: '2-kings', chapters: 25, testament: 'OT' },
  { id: '1ch', name: '1 Chroniques', apiName: '1 Chronicles', slug: '1-chronicles', chapters: 29, testament: 'OT' },
  { id: '2ch', name: '2 Chroniques', apiName: '2 Chronicles', slug: '2-chronicles', chapters: 36, testament: 'OT' },
  { id: 'ezr', name: 'Esdras', apiName: 'Ezra', slug: 'ezra', chapters: 10, testament: 'OT' },
  { id: 'neh', name: 'Néhémie', apiName: 'Nehemiah', slug: 'nehemiah', chapters: 13, testament: 'OT' },
  { id: 'est', name: 'Esther', apiName: 'Esther', slug: 'esther', chapters: 10, testament: 'OT' },
  { id: 'job', name: 'Job', apiName: 'Job', slug: 'job', chapters: 42, testament: 'OT' },
  { id: 'psa', name: 'Psaumes', apiName: 'Psalms', slug: 'psalms', chapters: 150, testament: 'OT' },
  { id: 'pro', name: 'Proverbes', apiName: 'Proverbs', slug: 'proverbs', chapters: 31, testament: 'OT' },
  { id: 'ecc', name: 'Ecclésiaste', apiName: 'Ecclesiastes', slug: 'ecclesiastes', chapters: 12, testament: 'OT' },
  { id: 'sng', name: 'Cantique des Cantiques', apiName: 'Song of Solomon', slug: 'song-of-solomon', chapters: 8, testament: 'OT' },
  { id: 'isa', name: 'Ésaïe', apiName: 'Isaiah', slug: 'isaiah', chapters: 66, testament: 'OT' },
  { id: 'jer', name: 'Jérémie', apiName: 'Jeremiah', slug: 'jeremiah', chapters: 52, testament: 'OT' },
  { id: 'lam', name: 'Lamentations', apiName: 'Lamentations', slug: 'lamentations', chapters: 5, testament: 'OT' },
  { id: 'ezk', name: 'Ézéchiel', apiName: 'Ezekiel', slug: 'ezekiel', chapters: 48, testament: 'OT' },
  { id: 'dan', name: 'Daniel', apiName: 'Daniel', slug: 'daniel', chapters: 12, testament: 'OT' },
  { id: 'hos', name: 'Osée', apiName: 'Hosea', slug: 'hosea', chapters: 14, testament: 'OT' },
  { id: 'jol', name: 'Joël', apiName: 'Joel', slug: 'joel', chapters: 3, testament: 'OT' },
  { id: 'amo', name: 'Amos', apiName: 'Amos', slug: 'amos', chapters: 9, testament: 'OT' },
  { id: 'oba', name: 'Abdias', apiName: 'Obadiah', slug: 'obadiah', chapters: 1, testament: 'OT' },
  { id: 'jon', name: 'Jonas', apiName: 'Jonah', slug: 'jonah', chapters: 4, testament: 'OT' },
  { id: 'mic', name: 'Michée', apiName: 'Micah', slug: 'micah', chapters: 7, testament: 'OT' },
  { id: 'nah', name: 'Nahum', apiName: 'Nahum', slug: 'nahum', chapters: 3, testament: 'OT' },
  { id: 'hab', name: 'Habacuc', apiName: 'Habakkuk', slug: 'habakkuk', chapters: 3, testament: 'OT' },
  { id: 'zep', name: 'Sophonie', apiName: 'Zephaniah', slug: 'zephaniah', chapters: 3, testament: 'OT' },
  { id: 'hag', name: 'Aggée', apiName: 'Haggai', slug: 'haggai', chapters: 2, testament: 'OT' },
  { id: 'zec', name: 'Zacharie', apiName: 'Zechariah', slug: 'zechariah', chapters: 14, testament: 'OT' },
  { id: 'mal', name: 'Malachie', apiName: 'Malachi', slug: 'malachi', chapters: 4, testament: 'OT' },
  { id: 'mat', name: 'Matthieu', apiName: 'Matthew', slug: 'matthew', chapters: 28, testament: 'NT' },
  { id: 'mrk', name: 'Marc', apiName: 'Mark', slug: 'mark', chapters: 16, testament: 'NT' },
  { id: 'luk', name: 'Luc', apiName: 'Luke', slug: 'luke', chapters: 24, testament: 'NT' },
  { id: 'jhn', name: 'Jean', apiName: 'John', slug: 'john', chapters: 21, testament: 'NT' },
  { id: 'act', name: 'Actes', apiName: 'Acts', slug: 'acts', chapters: 28, testament: 'NT' },
  { id: 'rom', name: 'Romains', apiName: 'Romans', slug: 'romans', chapters: 16, testament: 'NT' },
  { id: '1co', name: '1 Corinthiens', apiName: '1 Corinthians', slug: '1-corinthians', chapters: 16, testament: 'NT' },
  { id: '2co', name: '2 Corinthiens', apiName: '2 Corinthians', slug: '2-corinthians', chapters: 13, testament: 'NT' },
  { id: 'gal', name: 'Galates', apiName: 'Galatians', slug: 'galatians', chapters: 6, testament: 'NT' },
  { id: 'eph', name: 'Éphésiens', apiName: 'Ephesians', slug: 'ephesians', chapters: 6, testament: 'NT' },
  { id: 'php', name: 'Philippiens', apiName: 'Philippians', slug: 'philippians', chapters: 4, testament: 'NT' },
  { id: 'col', name: 'Colossiens', apiName: 'Colossians', slug: 'colossians', chapters: 4, testament: 'NT' },
  { id: '1th', name: '1 Thessaloniciens', apiName: '1 Thessalonians', slug: '1-thessalonians', chapters: 5, testament: 'NT' },
  { id: '2th', name: '2 Thessaloniciens', apiName: '2 Thessalonians', slug: '2-thessalonians', chapters: 3, testament: 'NT' },
  { id: '1ti', name: '1 Timothée', apiName: '1 Timothy', slug: '1-timothy', chapters: 6, testament: 'NT' },
  { id: '2ti', name: '2 Timothée', apiName: '2 Timothy', slug: '2-timothy', chapters: 4, testament: 'NT' },
  { id: 'tit', name: 'Tite', apiName: 'Titus', slug: 'titus', chapters: 3, testament: 'NT' },
  { id: 'phm', name: 'Philémon', apiName: 'Philemon', slug: 'philemon', chapters: 1, testament: 'NT' },
  { id: 'heb', name: 'Hébreux', apiName: 'Hebrews', slug: 'hebrews', chapters: 13, testament: 'NT' },
  { id: 'jas', name: 'Jacques', apiName: 'James', slug: 'james', chapters: 5, testament: 'NT' },
  { id: '1pe', name: '1 Pierre', apiName: '1 Peter', slug: '1-peter', chapters: 5, testament: 'NT' },
  { id: '2pe', name: '2 Pierre', apiName: '2 Peter', slug: '2-peter', chapters: 3, testament: 'NT' },
  { id: '1jo', name: '1 Jean', apiName: '1 John', slug: '1-john', chapters: 5, testament: 'NT' },
  { id: '2jo', name: '2 Jean', apiName: '2 John', slug: '2-john', chapters: 1, testament: 'NT' },
  { id: '3jo', name: '3 Jean', apiName: '3 John', slug: '3-john', chapters: 1, testament: 'NT' },
  { id: 'jud', name: 'Jude', apiName: 'Jude', slug: 'jude', chapters: 1, testament: 'NT' },
  { id: 'rev', name: 'Apocalypse', apiName: 'Revelation', slug: 'revelation', chapters: 22, testament: 'NT' },
];

export const TESTAMENTS = [
  { id: 'OT', label: 'Ancien Testament' },
  { id: 'NT', label: 'Nouveau Testament' },
];
